### ISSUE TITLE
There's no way to add individual revision dates to sub-branches in a main branch! (Option 1 of Setting Revision is not working)

### ISSUE THREAD

**Issue by senathenu** [SenaThenu/StudySphere#4]
_Your contributions are precious!_

**Comment by kaushalkumar99** [comment]
I am willing to contribute...please assign this to me.

**Comment by senathenu** [comment]
Thanks a lot, Kaushal. 😁

**Comment by kaushalkumar99** [comment]
Hi @SenaThenu, can you elaborate the issue so that i can try n solve the issue to it's best.

**Comment by senathenu** [comment]
Currently, the program recognises the option the user has selected (option 1 or 2) by checking whether the `global_revision_date` is empty in the `set_bulk_reps` function.
```py
if revision_rep:
    print(colored(f"🚀 Started Setting Revision to {branch}!", "blue"))
    if global_revision_date:
        revision_date = global_revision_date
    else:
        revision_date = get_user_input(colored(f"📅 Enter the revision date for {branch} (YYYY-MM-DD): ", "blue"), colored(f"😭 Sad to see you leaving while adding a Revision Date for {branch}!", "red"), colored("Just enter the date in the format YYYY-MM-DD! (e.g. 2077-05-09)", "magenta"), options=["YYYY-MM-DD"], match_length=True)
    set_reps_for_pages(branch_id, is_revision_rep=True, revision_date=revision_date)
    print(colored(f"Ended Setting Revision to {branch}!", "blue"))
```
(Line 321-332)

As you see, when it comes to sub-branches, the date the user set for the main branch is passed down to global_revision_date. So, every sub-branch is set to the same revision date. To prevent this, you have to specify a new parameter for the `set_bulk_reps` to access the option number the user selected. Let's say the new parameter is `revision_option`. Afterwards, the problem is pretty simple. You just have to rewrite the previous code block as;
```py
if revision_rep:
    print(colored(f"🚀 Started Setting Revision to {branch}!", "blue"))
    if revision_option == "2":
        revision_date = global_revision_date
    else
        revision_date = get_user_input(colored(f"📅 Enter the revision date for {branch} (YYYY-MM-DD): ", "blue"), colored(f"😭 Sad to see you leaving while adding a Revision Date for {branch}!", "red"), colored("Just enter the date in the format YYYY-MM-DD! (e.g. 2077-05-09)", "magenta"), options=["YYYY-MM-DD"], match_length=True)
    set_reps_for_pages(branch_id, is_revision_rep=True, revision_date=revision_date)
    print(colored(f"Ended Setting Revision to {branch}!", "blue"))
```
> **Note**
> The program takes the user's response as a string because there are only 2 options. Plus, make sure to add some documentation about the new parameter in the function's DocString! Good luck...🤞
